screen_width = 400  # ширина
screen_height = 600  # высота
FPS = 30  # кадры в секунду
platform_width = 50  # ширина платформы
platform_height = 5  # высота платформы
spring_width = 5     # ширина пружины
spring_height = 5    # высота пружины
max_vy_speed = 20
scroll_speed = 6
